// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TARge20.Data;

namespace TARge20.Data.Migrations
{
    [DbContext(typeof(TARge20DbContext))]
    [Migration("20210903112156_FirmaERD")]
    partial class FirmaERD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TARge20.Core.Domain.Ametinimetus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nimetus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ametinimetused");
                });

            modelBuilder.Entity("TARge20.Core.Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("TARge20.Core.Domain.Haigusleht", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Alguskuupäev")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Lõppkuupäev")
                        .HasColumnType("datetime2");

                    b.Property<string>("Põhjus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TöötajaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Haiguslehed");
                });

            modelBuilder.Entity("TARge20.Core.Domain.Laenutamine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Asi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Leanutuse_alguskuupäev")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Leanutuse_lõppkuupäev")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TöötajaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Laenutamised");
                });

            modelBuilder.Entity("TARge20.Core.Domain.Laps", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EesNimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Sünnipäev")
                        .HasColumnType("datetime2");

                    b.Property<int>("Vanus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Lapsed");
                });

            modelBuilder.Entity("TARge20.Core.Domain.Puhkus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Alguskuupäev")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Lõppkuupäev")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TöötajaID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Puhkused");
                });

            modelBuilder.Entity("TARge20.Core.Domain.Töötaja", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Ametinimetus_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EesNimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Haigusleht_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Laenutused_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Lapsed_ID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PerekonnaNimi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Puhkus_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Töötajad");
                });
#pragma warning restore 612, 618
        }
    }
}
